export const staffdata = [
    {
        id: "1001",
        name: "John Doe",
        email: "john_doe@gmail.com",
        department: "Production",
        designation: "Production Manager",
    },
    {
        id: "1002",
        name: "Joan Doe",
        email: "joan_doe@gmail.com",
        department: "Production",
        designation: "Senior Manager",
    },
    {
        id: "1003",
        name: "Jean Doe",
        email: "jean_doe@gmail.com",
        department: "Production",
        designation: "Junior Manager",
    },
    {
        id: "1004",
        name: "John Doe",
        email: "john_doe@gmail.com",
        department: "Production",
        designation: "Production Manager",
    },
    {
        id: "1005",
        name: "Joan Doe",
        email: "joan_doe@gmail.com",
        department: "Production",
        designation: "Senior Manager",
    },
    {
        id: "1006",
        name: "Jean Doe",
        email: "jean_doe@gmail.com",
        department: "Production",
        designation: "Junior Manager",
    },
    {
        id: "1007",
        name: "John Doe",
        email: "john_doe@gmail.com",
        department: "Production",
        designation: "Production Manager",
    },
    {
        id: "1008",
        name: "Joan Doe",
        email: "joan_doe@gmail.com",
        department: "Production",
        designation: "Senior Manager",
    },
    {
        id: "1009",
        name: "Jean Doe",
        email: "jean_doe@gmail.com",
        department: "Production",
        designation: "Junior Manager",
    },
    {
        id: "1010",
        name: "John Doe",
        email: "john_doe@gmail.com",
        department: "Production",
        designation: "Production Manager",
    },
    {
        id: "1011",
        name: "Joan Doe",
        email: "joan_doe@gmail.com",
        department: "Production",
        designation: "Senior Manager",
    },
    {
        id: "1012",
        name: "Joan Doe",
        email: "joan_doe@gmail.com",
        department: "Production",
        designation: "Senior Manager",
    },
    {
        id: "1013",
        name: "Jean Doe",
        email: "jean_doe@gmail.com",
        department: "Production",
        designation: "Junior Manager",
    },
    {
        id: "1014",
        name: "John Doe",
        email: "john_doe@gmail.com",
        department: "Production",
        designation: "Production Manager",
    },
    {
        id: "1015",
        name: "Joan Doe",
        email: "joan_doe@gmail.com",
        department: "Production",
        designation: "Senior Manager",
    },
    {
        id: "1016",
        name: "Jean Doe",
        email: "jean_doe@gmail.com",
        department: "Production",
        designation: "Junior Manager",
    },
    {
        id: "1017",
        name: "John Doe",
        email: "john_doe@gmail.com",
        department: "Production",
        designation: "Production Manager",
    },
    {
        id: "1018",
        name: "Joan Doe",
        email: "joan_doe@gmail.com",
        department: "Production",
        designation: "Senior Manager",
    },
    {
        id: "1019",
        name: "Jean Doe",
        email: "jean_doe@gmail.com",
        department: "Production",
        designation: "Junior Manager",
    },
    {
        id: "1020",
        name: "John Doe",
        email: "john_doe@gmail.com",
        department: "Production",
        designation: "Production Manager",
    },
    {
        id: "1021",
        name: "Joan Doe",
        email: "joan_doe@gmail.com",
        department: "Production",
        designation: "Senior Manager",
    },
    {
        id: "1022",
        name: "Jean Doe",
        email: "jean_doe@gmail.com",
        department: "Production",
        designation: "Junior Manager",
    },
    {
        id: "1023",
        name: "John Doe",
        email: "john_doe@gmail.com",
        department: "Production",
        designation: "Production Manager",
    },
    {
        id: "1024",
        name: "Joan Doe",
        email: "joan_doe@gmail.com",
        department: "Production",
        designation: "Senior Manager",
    },
    {
        id: "1025",
        name: "Jean Doe",
        email: "jean_doe@gmail.com",
        department: "Production",
        designation: "Junior Manager",
    },
    {
        id: "1026",
        name: "John Doe",
        email: "john_doe@gmail.com",
        department: "Production",
        designation: "Production Manager",
    },
    {
        id: "1027",
        name: "Joan Doe",
        email: "joan_doe@gmail.com",
        department: "Production",
        designation: "Senior Manager",
    },
    {
        id: "1028",
        name: "Jean Doe",
        email: "jean_doe@gmail.com",
        department: "Production",
        designation: "Junior Manager",
    },
    {
        id: "1029",
        name: "John Doe",
        email: "john_doe@gmail.com",
        department: "Production",
        designation: "Production Manager",
    },
    {
        id: "1030",
        name: "Joan Doe",
        email: "joan_doe@gmail.com",
        department: "Production",
        designation: "Senior Manager",
    },
]